version: '3.3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - redis

